name: 'api'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipython>=7.15
  - pandas
  - requests
  - altair
  - vega_datasets
  - pip:
    - isodate
    - plotly
    - plotly-express
    - ipython
    - dash
    - dash_bootstrap_components